services:
  postgres:
    image: postgres:14.3
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - ./.env
    ports:
      - "5432:5432"
    networks:
      - app-network

  api:
    build:
      context: .
      dockerfile: ./src/HowsYourDayAPI/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Production
    env_file:
      - ./.env
    ports:
      - "5000:8080"
    depends_on:
      - postgres
    networks:
      - app-network

  client:
    build:
      context: .
      dockerfile: ./src/HowsYourDayApp/Dockerfile
    ports:
      - "8080:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres-data: